# Generated by Django 4.0.1 on 2022-01-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suggestion_providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientVariantSwitchConfig",
            fields=[
                (
                    "providerconfig_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="suggestion_providers.providerconfig",
                    ),
                ),
                (
                    "client_variant",
                    models.CharField(
                        help_text="\n            If this string is found in a client_variants, the matching_provider \n            will be used for suggestions. If not, the default_provider will be \n            used.\n        ",
                        max_length=256,
                    ),
                ),
                (
                    "default_provider",
                    models.ForeignKey(
                        help_text="\nThe provider to use to generate suggestions.\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_variant_switch_default_provider",
                        to="suggestion_providers.providerconfig",
                    ),
                ),
                (
                    "matching_provider",
                    models.ForeignKey(
                        help_text="\nThe provider to use to generate suggestions.\n",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_variant_switch_matching_provider",
                        to="suggestion_providers.providerconfig",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("suggestion_providers.providerconfig",),
        ),
    ]
