version: 2
updates:
  # Merino Showroom
  - package-ecosystem: "npm"
    directory: "merino-showroom"
    schedule:
      interval: "daily"
    commit-message:
      # Add `[do not deploy]` to skip the auto deploy for this project
      prefix: "[do not deploy]"
