status = [
  "ci/circleci: build-and-test-%-sccache",
  "ci/circleci: checks",
]
# Avoid including verbose details from PR bodies
cut_body_after = "<details>"
block_labels = ["bors-dont-merge"]
delete_merged_branches = true
