services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: "local:redis:6379"

  statsd-logger:
    image: catkins/statsd-logger
    ports:
      - "8125:8125/udp"

  kinto:
    image: mozilla/kinto-dist:25.0.0
    stop_signal: SIGKILL
    user: "1000:1000"
    ports:
      - "8888:8888"
    volumes:
      - ./kinto.ini:/etc/kinto.ini
      - ./.kinto-attachments:/app/attachments
    environment:
      KINTO_INI: /etc/kinto.ini

  kinto-attachments:
    image: httpd
    depends_on:
      - kinto
    ports:
      - "8889:80"
    volumes:
      - ./.kinto-attachments:/usr/local/apache2/htdocs/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:
