version: "3"
services:
  merino:
    # See `docker-image-build` job in `.circleci/config.yml`
    image: app:runtime
    build: ../..
    container_name: merino
    environment:
      # The configuration preset to use
      MERINO_ENV: "ci"
      MERINO_REMOTE_SETTINGS__DEFAULT_BUCKET: main
      MERINO_REMOTE_SETTINGS__DEFAULT_COLLECTION: quicksuggest
      MERINO_REMOTE_SETTINGS__SERVER: http://kinto:8888
    depends_on:
      - kinto
      - kinto-attachments
      - kinto-setup
    volumes:
      - ../../dev:/tmp/dev
    command: >
      sh -c 'sleep 10 && /app/bin/merino'

  client:
    image: client
    build: client
    container_name: merino_client
    depends_on:
      - merino
    volumes:
      - ./volumes/client:/tmp/client
      - ./volumes/kinto:/tmp/kinto
      - ../../dev/wait-for-it.sh:/wait-for-it.sh
    environment:
      MERINO_URL: http://merino:8000
      SCENARIOS_FILE: /tmp/client/scenarios.yml
      KINTO_URL: http://kinto:8888
      KINTO_BUCKET: main
      KINTO_COLLECTION: quicksuggest
      KINTO_DATA_DIR: /tmp/kinto
      KINTO_ATTACHMENTS_URL: http://kinto-attachments
    command: >
      /wait-for-it.sh merino:8000 --strict -- pytest -vv

  kinto:
    image: mozilla/kinto-dist:25.0.0
    container_name: merino_kinto
    stop_signal: SIGKILL
    user: "1000:1000"
    volumes:
      - ../../dev/kinto.ini:/etc/kinto.ini
      - ./kinto-attachments:/app/attachments:rw
    environment:
      KINTO_INI: /etc/kinto.ini
      # We need to overwrite the following setting for contract-tests
      KINTO_ATTACHMENT_EXTRA_BASE_URL: http://kinto-attachments:80

  kinto-attachments:
    image: httpd
    container_name: merino_kinto_attachments
    depends_on:
      - kinto
    volumes:
      - ./kinto-attachments:/usr/local/apache2/htdocs/

  kinto-setup:
    image: kinto-setup
    build: kinto-setup
    container_name: merino_kinto_setup
    depends_on:
      - kinto
      - kinto-attachments
    volumes:
      - ./volumes/kinto:/tmp/kinto
      - ../../dev/wait-for-it.sh:/wait-for-it.sh
    environment:
      KINTO_URL: http://kinto:8888
      KINTO_BUCKET: main
      KINTO_COLLECTION: quicksuggest
      KINTO_DATA_DIR: /tmp/kinto
    command: >
      /wait-for-it.sh kinto:8888 --strict -- python main.py
