version: "3"
services:
  merino:
    # See `docker-image-build` job in `.circleci/config.yml`
    image: app:runtime
    build: ../..
    container_name: merino
    environment:
      # The configuration preset to use
      MERINO_ENV: "ci"
    volumes:
      - ../../dev:/tmp/dev

  client:
    image: client
    build: client
    container_name: merino_client
    depends_on:
      - merino
    volumes:
      - ./volumes/client:/tmp/client
      - ../../dev/wait-for-it.sh:/wait-for-it.sh
    environment:
      MERINO_URL: http://merino:8000
      SCENARIOS_FILE: /tmp/client/scenarios.yml
    command: >
      /wait-for-it.sh merino:8000 --strict -- pytest -vv
