# Enable additional features to debug the application
debug: true

http:
  # The host and port Merino listens on
  listen: "0.0.0.0:8000"
  # Limit the number of HTTP workers
  workers: 1

location:
  # The location of the maxmind database to use to determine IP location
  maxmind_database: "/tmp/dev/GeoLite2-City-Test.mmdb"

logging:
  # Print logs in a verbose, formatted format
  format: pretty
  # The minimum level that logs should be reported at
  levels: ["DEBUG"]

sentry:
  mode: "disabled"

provider_settings:
  type: local
  path: ./config/providers/ci.yaml
  cron_interval_sec: 1
