debug: true

logging:
  format: pretty

suggestion_providers:
  adm:
    type: remote_settings
    collection: "quicksuggest"
  wiki_fruit:
    type: wiki_fruit
  debug:
    type: debug

location:
  maxmind_database: "./dev/GeoLite2-City-Test.mmdb"

sentry:
  mode: debug
