debug: true

logging:
  format: pretty

location:
  maxmind_database: "./dev/GeoLite2-City-Test.mmdb"

sentry:
  mode: local_debug

provider_settings:
  type: local
  path: ./config/providers/development.yaml
