debug: true

logging:
  format: pretty

providers:
  adm_rs:
    enabled: true
    storage_path: "./rs-cache"
    collection: "quicksuggest"
  wiki_fruit:
    enabled: true
  enable_debug_provider: true

location:
  maxmind_database: "./dev/GeoLite2-City-Test.mmdb"

sentry:
  mode: debug
