--- # Suggestion providers
test_wiki_fruit:
  type: wiki_fruit
adm:
  type: memory_cache
  inner:
    type: remote_settings
    collection: quicksuggest
    suggestion_score: 0.3
    resync_interval_sec: 2
